### ISSUE TITLE
InsecurePlatformWarning

### ISSUE THREAD

**Issue by allanlaal** [ksiazkowicz/orphilia-dropbox#13]
when running --delta I sometimes get:

/afs/devices/L3/opt/orphilia-dropbox/orphilia/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

this is shown apparently randomly when some files are syncing

**Comment by ksiazkowicz** [comment]
Try updating Python to 2.7.9

https://renoirboulanger.com/blog/2015/04/upgrade-python-2-7-9-ubuntu-14-04-lts-making-deb-package/
