### ISSUE TITLE
Orphilia not building properly on Latest Haiku

### ISSUE THREAD

**Issue by richienyhus** [ksiazkowicz/orphilia-dropbox#8]
Here is the GCI2013 task for it:
http://www.google-melange.com/gci/task/view/google/gci2013/5534833086300160

HaikuPorts is tracking the software that will be included in Haiku's package manager that will come with Haiku R1 Beta1, this is expected to be released in the new year.

HaikuPorts:
haikuports.org

**Comment by pulkomandy** [comment]
Hi,
This issue was solved on Haiku side, and can be closed. The client builds just fine now.

**Comment by ksiazkowicz** [comment]
Thanks for the heads up!

It's important to note that I switched to pip lately and on Haiku it needs to be installed using get-pip.py script.

It seems to be working fine right now (hrev49880).
![2015-11-24_23-35-17](https://cloud.githubusercontent.com/assets/1162358/11382797/450f7922-9304-11e5-9587-3cc53d4df4ab.png)
